package ir.tinydeveloper.fallingwords.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006E0A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF45D32E)
val md_theme_light_onPrimaryContainer = Color(0xFF002201)
val md_theme_light_secondary = Color(0xFF53634E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E8CD)
val md_theme_light_onSecondaryContainer = Color(0xFF111F0F)
val md_theme_light_tertiary = Color(0xFF825500)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB4)
val md_theme_light_onTertiaryContainer = Color(0xFF291800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFFDC)
val md_theme_light_onBackground = Color(0xFF191E00)
val md_theme_light_surface = Color(0xFFFCFFDC)
val md_theme_light_onSurface = Color(0xFF191E00)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D8)
val md_theme_light_onSurfaceVariant = Color(0xFF42493F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFE9FA86)
val md_theme_light_inverseSurface = Color(0xFF3E4700)
val md_theme_light_inversePrimary = Color(0xFF76DD68)
val md_theme_light_surfaceTint = Color(0xFF006E0A)
val md_theme_light_outlineVariant = Color(0xFFC2C8BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF76DD68)
val md_theme_dark_onPrimary = Color(0xFF003A03)
val md_theme_dark_primaryContainer = Color(0xFF005305)
val md_theme_dark_onPrimaryContainer = Color(0xFF92FA81)
val md_theme_dark_secondary = Color(0xFFBBCCB2)
val md_theme_dark_onSecondary = Color(0xFF263422)
val md_theme_dark_secondaryContainer = Color(0xFF3C4B37)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E8CD)
val md_theme_dark_tertiary = Color(0xFFFFB952)
val md_theme_dark_onTertiary = Color(0xFF452B00)
val md_theme_dark_tertiaryContainer = Color(0xFF633F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191E00)
val md_theme_dark_onBackground = Color(0xFFDBEC79)
val md_theme_dark_surface = Color(0xFF191E00)
val md_theme_dark_onSurface = Color(0xFFDBEC79)
val md_theme_dark_surfaceVariant = Color(0xFF42493F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C8BC)
val md_theme_dark_outline = Color(0xFF8C9387)
val md_theme_dark_inverseOnSurface = Color(0xFF191E00)
val md_theme_dark_inverseSurface = Color(0xFFDBEC79)
val md_theme_dark_inversePrimary = Color(0xFF006E0A)
val md_theme_dark_surfaceTint = Color(0xFF76DD68)
val md_theme_dark_outlineVariant = Color(0xFF42493F)
val md_theme_dark_scrim = Color(0xFF000000)

val TransactionLight = Color(0xFFEEFF00)
val SharePaymentLight = Color(0xFFA6FF00)
val ReceiveLoanLight = Color(0xFFF44336)

val TransactionDark = Color(0xFF797E40)
val SharePaymentDark = Color(0xFF4E6F12)
val ReceiveLoanDark = Color(0xFF720A02)
